/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//

/*
        GABRIEL MENDEZ VANEGAS
        ELECTIVA PROFESIONAL III
        INGENIERIA DE SISTEMAS
        UNIVERSIDAD DE CUNDINAMARCA

*/
package programaa1;

import javax.swing.JOptionPane;

/**
 *
 * @author Mendez
 */
public class Aplicacion1 extends javax.swing.JFrame {

   
    
    /**
     * Creates new form Aplicacion1
     */
    public Aplicacion1() {
        initComponents(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcesar = new javax.swing.JButton();
        txtTexto = new javax.swing.JTextField();
        txtRespuesta = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        txtTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTextoKeyReleased(evt);
            }
        });

        txtRespuesta.setEditable(false);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcesar)
                        .addGap(43, 43, 43)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRespuesta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnNuevo)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
      
        for(int i=0; i < this.txtTexto.getText().length();i++)
        {
            char letra = this.txtTexto.getText().charAt(i);
            switch (letra)
            {case 'A':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"Z");
                break;
            case 'B':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"Y");
                break;
            case 'C':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"X");
                break;
            case 'D':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"W");
                break;
            case 'E':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"V");
                break;
            case 'F':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"U");
                break;
            case 'G':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"T");
                break;
            case 'H':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"S");
                break;
            case 'I':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"R");
                break;
            case 'J':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"Q");
                break;    
            case 'K':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"P");
                break;
            case 'L':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"O");
                break;
            case 'M':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"N");
                break;
            case 'N':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"M");
                break;
            case 'O':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"L");
                break;
            case 'P':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"K");
                break;
            case 'Q':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"J");
                break;
            case 'R':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"I");
                break;
            case 'S':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"H");
                break;
            case 'T':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"G");
                break;
            case 'U':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"F");
                break;
            case 'V':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"E");
                break;
            case 'W':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"D");
                break;
            case 'X':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"C");
                break;
            case 'Y':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"B");
                break;
            case 'Z':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+"A");
                break;
            case ' ':
                this.txtRespuesta.setText(this.txtRespuesta.getText()+" ");
                break;    
            default:
                break;
            }
        }
        
        this.btnProcesar.setEnabled(false);
        
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void txtTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoKeyReleased
        // TODO add your handling code here:
         this.txtTexto.setText(this.txtTexto.getText().toUpperCase());
   
    }//GEN-LAST:event_txtTextoKeyReleased

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.btnProcesar.setEnabled(true);
        this.txtTexto.setText("");
        this.txtRespuesta.setText("");
        this.txtTexto.grabFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
